apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql-1
    app.kubernetes.io/component: feedback-service-db
    app.kubernetes.io/part-of: feedback-service
    app.kubernetes.io/managed-by: Kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
