apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  serviceName: postgresql
  replicas: 1  
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: postgresql-1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/instance: postgresql-1
    spec:
      restartPolicy: Always
      containers:
      - name: postgresql
        image: postgres:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgresql-config
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: password
          - name: POSTGRES_DB
            value: feedback
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-pvc
