apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  SPRING_CONFIG_IMPORT: "configserver:http://config-server-svc:9296/"
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_SERVICE_ADDRESS: "http://eureka:8761/eureka"

