apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql-1
  clusterIP: None
  type: ClusterIP
