apiVersion: v1
kind: Service
metadata:
  name: postgresql-service-np
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql-1
    app.kubernetes.io/component: feedback-service-db
    app.kubernetes.io/part-of: feedback-service
    app.kubernetes.io/managed-by: Kubernetes
spec:
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql-1
  type: NodePort
  ports:
    - port: 5432
 
