apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql-1
    app.kubernetes.io/component: feedback-service-db
    app.kubernetes.io/part-of: feedback-service
    app.kubernetes.io/managed-by: Kubernetes
spec:
  serviceName: postgresql
  replicas: 1  
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: postgresql-1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/instance: postgresql-1
    spec:
      restartPolicy: Always
      containers:
      - name: postgresql
        image: postgres:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_DB
          value: feedback
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: password
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-pvc
