apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  serviceName: "eureka"
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: matteosevergninistudent/server-registry:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_SERVICE_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: EUREKA_SERVICE_ADDRESS
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
<<<<<<< HEAD
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: SPRING_PROFILES_ACTIVE
            - name: REGISTRY_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: REGISTRY_HOSTNAME
=======
                  key: SPRING_CONFIG_IMPORT
>>>>>>> parent of 5566f9a (fixed)
